### ISSUE TITLE
Missing conversion to int for data from memcached during stats command

### ISSUE THREAD

**Issue by ddossett** [hep-gc/dynafed_storagestats#114]
When doing `dynafed-storage stats` before the timeout/expiry the values are queried from memcached. But some are calculated, for example the "bytesfree" value is calculated by subtracting the "bytesused" from the value of "quota".

https://github.com/hep-gc/dynafed_storagestats/blob/master/dynafed_storagestats/helpers.py#L753

However the value of "bytesused" hasn't been converted to a integer type and is actually a string, causing this error:

```
(.env) [root@dynafed-testing ~]# dynafed-storage stats -v -c /etc/ugr/conf.d -m --stdout
2022-11-03 04:42:13,351 - [ERROR][TEST][PeriodNotReached]Bypassing stats check.
Traceback (most recent call last):
  File "/etc/ugr/conf.d/.env/bin/dynafed-storage", line 11, in <module>
    load_entry_point('dynafed-storagestats==1.0.40', 'console_scripts', 'dynafed-storage')()
  File "/etc/ugr/conf.d/.env/lib64/python3.6/site-packages/dynafed_storagestats/runner.py", line 42, in main
    stats(ARGS)
  File "/etc/ugr/conf.d/.env/lib64/python3.6/site-packages/dynafed_storagestats/runner.py", line 248, in stats
    storage_endpoints_list_and_args_tuple
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/etc/ugr/conf.d/.env/lib64/python3.6/site-packages/dynafed_storagestats/helpers.py", line 1001, in process_storagestats
    process_endpoint_list_results(storage_endpoint.storage_shares)
  File "/etc/ugr/conf.d/.env/lib64/python3.6/site-packages/dynafed_storagestats/helpers.py", line 757, in process_endpoint_list_results
    - storage_share_objects[_storage_share].stats['bytesused']
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

The fix is easy, I think the best place is to use `int()` to convert the three values to integers when creating the dictionary of stats here:

https://github.com/hep-gc/dynafed_storagestats/blob/master/dynafed_storagestats/helpers.py#L479

It works for me so far. I can submit a PR for the change if you like?

**Comment by MarcusEbert** [comment]
Which version are you using? I can not reproduce the issue in the latest version.

**Comment by MarcusEbert** [comment]
Could you please try the version that is in pypi (via pip3)?

**Comment by ddossett** [comment]
Using the pip version still has the error, I'm using a venv of python 3.6.8 at the moment.

```
[root@dynafed-testing ~]# source /etc/ugr/conf.d/.env/bin/activate
(.env) [root@dynafed-testing ~]# python --version
Python 3.6.8
(.env) [root@dynafed-testing ~]# python -m pip install dynafed-storagestats
...
(.env) [root@dynafed-testing ~]# dynafed-storage --version
1.0.40
(.env) [root@dynafed-testing ~]# dynafed-storage stats -v -c /etc/ugr/conf.d -m --stdout
2022-11-04 04:03:32,259 - [ERROR][MemcachedIndexError][082]Unable to get memcached index contents. Memcache Server 127.0.0.1:11211 did not return data. All storage_shares will be assumed 'Online'.
2022-11-04 04:03:32,261 - [ERROR][TEST][PeriodNotReached]Bypassing stats check.
Traceback (most recent call last):
  File "/etc/ugr/conf.d/.env/bin/dynafed-storage", line 8, in <module>
    sys.exit(main())
...
  File "/etc/ugr/conf.d/.env/lib64/python3.6/site-packages/dynafed_storagestats/helpers.py", line 754, in process_endpoint_list_results
    - storage_share_objects[_storage_share].stats['bytesused']
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

I tried altering the quota in the locplugin conf to be in bytes rather than my usual 500gib (see below), but that didn't fix the error :(

```
locplugin.TEST.storagestats.quota: 536870912000
locplugin.TEST.storagestats.frequency: 1800
locplugin.TEST.storagestats.api: generic
```
