### ISSUE TITLE
Boto Error

### ISSUE THREAD

**Issue by ffgalindo** [hep-gc/dynafed_storagestats#50]
While testing we got an error with Boto once (did not reproduce on subsequent times) and crashed the script with the following:
Need to investigate what this means and why it was not caught by the exception handler. 
```
Traceback (most recent call last):
  File "./dynafed_storagestats.py", line 151, in <module>
    main()
  File "./dynafed_storagestats.py", line 127, in main
    pool.starmap(helpers.process_storagestats, storage_endpoints_list_and_args_tuple)
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 298, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/fernando/lab/dynafedstoragestats/dynafedstoragestats/helpers.py", line 244, in process_storagestats
    storage_endpoint.storageshares[0].get_storagestats()
  File "/home/fernando/lab/dynafedstoragestats/dynafedstoragestats/s3/base.py", line 106, in get_storagestats
    s3helpers.list_objects(self)
  File "/home/fernando/lab/dynafedstoragestats/dynafedstoragestats/s3/helpers.py", line 246, in list_objects
    retries=dict(max_attempts=0)
  File "/usr/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/lib/python3.7/site-packages/botocore/session.py", line 851, in create_client
    endpoint_resolver = self.get_component('endpoint_resolver')
  File "/usr/lib/python3.7/site-packages/botocore/session.py", line 726, in get_component
    return self._components.get_component(name)
  File "/usr/lib/python3.7/site-packages/botocore/session.py", line 926, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'
```

**Comment by ffgalindo** [comment]
This was fixed in #78
